version: '3.8'

services:
  symfony:
    image: lamineur
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/lamineur
    networks:
      - mynetwork
    restart: always  
   # command: /var/www/docker/script.sh  # Utiliser le script

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www  
    depends_on:
      - symfony
    ports:
      - "8080:80"
    networks:
      - mynetwork
    restart: always  

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamineur
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    restart: always  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - mynetwork
    restart: always  

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
